[package]
name = "ir-zkp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prover"

[[bin]]
name = "verifier"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
